<?php
/**
 * Handler
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ory\Hydra
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Hydra OAuth2 & OpenID Connect Server
 *
 * Please refer to the user guide for in-depth documentation: https://ory.gitbooks.io/hydra/content/  Hydra offers OAuth 2.0 and OpenID Connect Core 1.0 capabilities as a service. Hydra is different, because it works with any existing authentication infrastructure, not just LDAP or SAML. By implementing a consent app (works with any programming language) you build a bridge between Hydra and your authentication infrastructure. Hydra is able to securely manage JSON Web Keys, and has a sophisticated policy-based access control you can use if you want to. Hydra is suitable for green- (new) and brownfield (existing) projects. If you are not familiar with OAuth 2.0 and are working on a greenfield project, we recommend evaluating if OAuth 2.0 really serves your purpose. Knowledge of OAuth 2.0 is imperative in understanding what Hydra does and how it works.  The official repository is located at https://github.com/ory/hydra
 *
 * OpenAPI spec version: Latest
 * Contact: hi@ory.am
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Ory\Hydra\Model;

use \ArrayAccess;

/**
 * Handler Class Doc Comment
 *
 * @category    Class
 * @package     Ory\Hydra
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Handler implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'Handler';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'access_token_lifespan' => '\Ory\Hydra\Model\Duration',
        'consent' => '\Ory\Hydra\Model\ConsentStrategy',
        'consent_url' => '\Ory\Hydra\Model\URL',
        'cookie_store' => '\Ory\Hydra\Model\Store',
        'forced_http' => 'bool',
        'h' => '\Ory\Hydra\Model\Writer',
        'issuer' => 'string',
        'l' => '\Ory\Hydra\Model\FieldLogger',
        'o_auth2' => '\Ory\Hydra\Model\OAuth2Provider'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerFormats = [
        'access_token_lifespan' => null,
        'consent' => null,
        'consent_url' => null,
        'cookie_store' => null,
        'forced_http' => null,
        'h' => null,
        'issuer' => null,
        'l' => null,
        'o_auth2' => null
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'access_token_lifespan' => 'AccessTokenLifespan',
        'consent' => 'Consent',
        'consent_url' => 'ConsentURL',
        'cookie_store' => 'CookieStore',
        'forced_http' => 'ForcedHTTP',
        'h' => 'H',
        'issuer' => 'Issuer',
        'l' => 'L',
        'o_auth2' => 'OAuth2'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'access_token_lifespan' => 'setAccessTokenLifespan',
        'consent' => 'setConsent',
        'consent_url' => 'setConsentUrl',
        'cookie_store' => 'setCookieStore',
        'forced_http' => 'setForcedHttp',
        'h' => 'setH',
        'issuer' => 'setIssuer',
        'l' => 'setL',
        'o_auth2' => 'setOAuth2'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'access_token_lifespan' => 'getAccessTokenLifespan',
        'consent' => 'getConsent',
        'consent_url' => 'getConsentUrl',
        'cookie_store' => 'getCookieStore',
        'forced_http' => 'getForcedHttp',
        'h' => 'getH',
        'issuer' => 'getIssuer',
        'l' => 'getL',
        'o_auth2' => 'getOAuth2'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['access_token_lifespan'] = isset($data['access_token_lifespan']) ? $data['access_token_lifespan'] : null;
        $this->container['consent'] = isset($data['consent']) ? $data['consent'] : null;
        $this->container['consent_url'] = isset($data['consent_url']) ? $data['consent_url'] : null;
        $this->container['cookie_store'] = isset($data['cookie_store']) ? $data['cookie_store'] : null;
        $this->container['forced_http'] = isset($data['forced_http']) ? $data['forced_http'] : null;
        $this->container['h'] = isset($data['h']) ? $data['h'] : null;
        $this->container['issuer'] = isset($data['issuer']) ? $data['issuer'] : null;
        $this->container['l'] = isset($data['l']) ? $data['l'] : null;
        $this->container['o_auth2'] = isset($data['o_auth2']) ? $data['o_auth2'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets access_token_lifespan
     * @return \Ory\Hydra\Model\Duration
     */
    public function getAccessTokenLifespan()
    {
        return $this->container['access_token_lifespan'];
    }

    /**
     * Sets access_token_lifespan
     * @param \Ory\Hydra\Model\Duration $access_token_lifespan
     * @return $this
     */
    public function setAccessTokenLifespan($access_token_lifespan)
    {
        $this->container['access_token_lifespan'] = $access_token_lifespan;

        return $this;
    }

    /**
     * Gets consent
     * @return \Ory\Hydra\Model\ConsentStrategy
     */
    public function getConsent()
    {
        return $this->container['consent'];
    }

    /**
     * Sets consent
     * @param \Ory\Hydra\Model\ConsentStrategy $consent
     * @return $this
     */
    public function setConsent($consent)
    {
        $this->container['consent'] = $consent;

        return $this;
    }

    /**
     * Gets consent_url
     * @return \Ory\Hydra\Model\URL
     */
    public function getConsentUrl()
    {
        return $this->container['consent_url'];
    }

    /**
     * Sets consent_url
     * @param \Ory\Hydra\Model\URL $consent_url
     * @return $this
     */
    public function setConsentUrl($consent_url)
    {
        $this->container['consent_url'] = $consent_url;

        return $this;
    }

    /**
     * Gets cookie_store
     * @return \Ory\Hydra\Model\Store
     */
    public function getCookieStore()
    {
        return $this->container['cookie_store'];
    }

    /**
     * Sets cookie_store
     * @param \Ory\Hydra\Model\Store $cookie_store
     * @return $this
     */
    public function setCookieStore($cookie_store)
    {
        $this->container['cookie_store'] = $cookie_store;

        return $this;
    }

    /**
     * Gets forced_http
     * @return bool
     */
    public function getForcedHttp()
    {
        return $this->container['forced_http'];
    }

    /**
     * Sets forced_http
     * @param bool $forced_http
     * @return $this
     */
    public function setForcedHttp($forced_http)
    {
        $this->container['forced_http'] = $forced_http;

        return $this;
    }

    /**
     * Gets h
     * @return \Ory\Hydra\Model\Writer
     */
    public function getH()
    {
        return $this->container['h'];
    }

    /**
     * Sets h
     * @param \Ory\Hydra\Model\Writer $h
     * @return $this
     */
    public function setH($h)
    {
        $this->container['h'] = $h;

        return $this;
    }

    /**
     * Gets issuer
     * @return string
     */
    public function getIssuer()
    {
        return $this->container['issuer'];
    }

    /**
     * Sets issuer
     * @param string $issuer
     * @return $this
     */
    public function setIssuer($issuer)
    {
        $this->container['issuer'] = $issuer;

        return $this;
    }

    /**
     * Gets l
     * @return \Ory\Hydra\Model\FieldLogger
     */
    public function getL()
    {
        return $this->container['l'];
    }

    /**
     * Sets l
     * @param \Ory\Hydra\Model\FieldLogger $l
     * @return $this
     */
    public function setL($l)
    {
        $this->container['l'] = $l;

        return $this;
    }

    /**
     * Gets o_auth2
     * @return \Ory\Hydra\Model\OAuth2Provider
     */
    public function getOAuth2()
    {
        return $this->container['o_auth2'];
    }

    /**
     * Sets o_auth2
     * @param \Ory\Hydra\Model\OAuth2Provider $o_auth2
     * @return $this
     */
    public function setOAuth2($o_auth2)
    {
        $this->container['o_auth2'] = $o_auth2;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Ory\Hydra\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Ory\Hydra\ObjectSerializer::sanitizeForSerialization($this));
    }
}


