<?php
/**
 * WellKnownTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ory\Hydra
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Hydra OAuth2 & OpenID Connect Server
 *
 * Please refer to the user guide for in-depth documentation: https://ory.gitbooks.io/hydra/content/  Hydra offers OAuth 2.0 and OpenID Connect Core 1.0 capabilities as a service. Hydra is different, because it works with any existing authentication infrastructure, not just LDAP or SAML. By implementing a consent app (works with any programming language) you build a bridge between Hydra and your authentication infrastructure. Hydra is able to securely manage JSON Web Keys, and has a sophisticated policy-based access control you can use if you want to. Hydra is suitable for green- (new) and brownfield (existing) projects. If you are not familiar with OAuth 2.0 and are working on a greenfield project, we recommend evaluating if OAuth 2.0 really serves your purpose. Knowledge of OAuth 2.0 is imperative in understanding what Hydra does and how it works.  The official repository is located at https://github.com/ory/hydra
 *
 * OpenAPI spec version: Latest
 * Contact: hi@ory.am
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Ory\Hydra;

/**
 * WellKnownTest Class Doc Comment
 *
 * @category    Class */
// * @description WellKnown
/**
 * @package     Ory\Hydra
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class WellKnownTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "WellKnown"
     */
    public function testWellKnown()
    {
    }

    /**
     * Test attribute "authorization_endpoint"
     */
    public function testPropertyAuthorizationEndpoint()
    {
    }

    /**
     * Test attribute "id_token_signing_alg_values_supported"
     */
    public function testPropertyIdTokenSigningAlgValuesSupported()
    {
    }

    /**
     * Test attribute "issuer"
     */
    public function testPropertyIssuer()
    {
    }

    /**
     * Test attribute "jwks_uri"
     */
    public function testPropertyJwksUri()
    {
    }

    /**
     * Test attribute "response_types_supported"
     */
    public function testPropertyResponseTypesSupported()
    {
    }

    /**
     * Test attribute "subject_types_supported"
     */
    public function testPropertySubjectTypesSupported()
    {
    }

    /**
     * Test attribute "token_endpoint"
     */
    public function testPropertyTokenEndpoint()
    {
    }
}
